// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: pb/academy.proto

package grabber

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Academy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Abbreviation    string   `protobuf:"bytes,3,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	Alias           string   `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Website         string   `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	Endpoint        string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Version         string   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	DisabledSources []string `protobuf:"bytes,8,rep,name=disabled_sources,json=disabledSources,proto3" json:"disabled_sources,omitempty"`
	IsDisabled      int32    `protobuf:"varint,9,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
}

func (x *Academy) Reset() {
	*x = Academy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_academy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Academy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Academy) ProtoMessage() {}

func (x *Academy) ProtoReflect() protoreflect.Message {
	mi := &file_pb_academy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Academy.ProtoReflect.Descriptor instead.
func (*Academy) Descriptor() ([]byte, []int) {
	return file_pb_academy_proto_rawDescGZIP(), []int{0}
}

func (x *Academy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Academy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Academy) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *Academy) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Academy) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Academy) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Academy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Academy) GetDisabledSources() []string {
	if x != nil {
		return x.DisabledSources
	}
	return nil
}

func (x *Academy) GetIsDisabled() int32 {
	if x != nil {
		return x.IsDisabled
	}
	return 0
}

type GetAcademyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAcademyRequest) Reset() {
	*x = GetAcademyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_academy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAcademyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAcademyRequest) ProtoMessage() {}

func (x *GetAcademyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_academy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAcademyRequest.ProtoReflect.Descriptor instead.
func (*GetAcademyRequest) Descriptor() ([]byte, []int) {
	return file_pb_academy_proto_rawDescGZIP(), []int{1}
}

func (x *GetAcademyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAcademiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAcademiesRequest) Reset() {
	*x = ListAcademiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_academy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAcademiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAcademiesRequest) ProtoMessage() {}

func (x *ListAcademiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_academy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAcademiesRequest.ProtoReflect.Descriptor instead.
func (*ListAcademiesRequest) Descriptor() ([]byte, []int) {
	return file_pb_academy_proto_rawDescGZIP(), []int{2}
}

type ListAcademiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Academy `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListAcademiesResponse) Reset() {
	*x = ListAcademiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_academy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAcademiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAcademiesResponse) ProtoMessage() {}

func (x *ListAcademiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_academy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAcademiesResponse.ProtoReflect.Descriptor instead.
func (*ListAcademiesResponse) Descriptor() ([]byte, []int) {
	return file_pb_academy_proto_rawDescGZIP(), []int{3}
}

func (x *ListAcademiesResponse) GetData() []*Academy {
	if x != nil {
		return x.Data
	}
	return nil
}

type SearchAcademiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Term string `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *SearchAcademiesRequest) Reset() {
	*x = SearchAcademiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_academy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchAcademiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAcademiesRequest) ProtoMessage() {}

func (x *SearchAcademiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_academy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAcademiesRequest.ProtoReflect.Descriptor instead.
func (*SearchAcademiesRequest) Descriptor() ([]byte, []int) {
	return file_pb_academy_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAcademiesRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

var File_pb_academy_proto protoreflect.FileDescriptor

var file_pb_academy_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x22, 0x83, 0x02, 0x0a, 0x07,
	0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61,
	0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x62, 0x62, 0x72, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x69, 0x73, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x64, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63,
	0x61, 0x64, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e,
	0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a,
	0x16, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x32, 0xa0, 0x01, 0x0a, 0x0e,
	0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x12, 0x1a, 0x2e, 0x67,
	0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62,
	0x65, 0x72, 0x2e, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65, 0x6d, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e,
	0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x61, 0x64,
	0x65, 0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67,
	0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x61, 0x64, 0x65,
	0x6d, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_academy_proto_rawDescOnce sync.Once
	file_pb_academy_proto_rawDescData = file_pb_academy_proto_rawDesc
)

func file_pb_academy_proto_rawDescGZIP() []byte {
	file_pb_academy_proto_rawDescOnce.Do(func() {
		file_pb_academy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_academy_proto_rawDescData)
	})
	return file_pb_academy_proto_rawDescData
}

var file_pb_academy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_academy_proto_goTypes = []interface{}{
	(*Academy)(nil),                // 0: grabber.Academy
	(*GetAcademyRequest)(nil),      // 1: grabber.GetAcademyRequest
	(*ListAcademiesRequest)(nil),   // 2: grabber.ListAcademiesRequest
	(*ListAcademiesResponse)(nil),  // 3: grabber.ListAcademiesResponse
	(*SearchAcademiesRequest)(nil), // 4: grabber.SearchAcademiesRequest
}
var file_pb_academy_proto_depIdxs = []int32{
	0, // 0: grabber.ListAcademiesResponse.data:type_name -> grabber.Academy
	1, // 1: grabber.AcademyService.GetAcademy:input_type -> grabber.GetAcademyRequest
	2, // 2: grabber.AcademyService.ListAcademies:input_type -> grabber.ListAcademiesRequest
	0, // 3: grabber.AcademyService.GetAcademy:output_type -> grabber.Academy
	3, // 4: grabber.AcademyService.ListAcademies:output_type -> grabber.ListAcademiesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_academy_proto_init() }
func file_pb_academy_proto_init() {
	if File_pb_academy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_academy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Academy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_academy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAcademyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_academy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAcademiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_academy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAcademiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_academy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchAcademiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_academy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_academy_proto_goTypes,
		DependencyIndexes: file_pb_academy_proto_depIdxs,
		MessageInfos:      file_pb_academy_proto_msgTypes,
	}.Build()
	File_pb_academy_proto = out.File
	file_pb_academy_proto_rawDesc = nil
	file_pb_academy_proto_goTypes = nil
	file_pb_academy_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AcademyServiceClient is the client API for AcademyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AcademyServiceClient interface {
	GetAcademy(ctx context.Context, in *GetAcademyRequest, opts ...grpc.CallOption) (*Academy, error)
	ListAcademies(ctx context.Context, in *ListAcademiesRequest, opts ...grpc.CallOption) (*ListAcademiesResponse, error)
}

type academyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAcademyServiceClient(cc grpc.ClientConnInterface) AcademyServiceClient {
	return &academyServiceClient{cc}
}

func (c *academyServiceClient) GetAcademy(ctx context.Context, in *GetAcademyRequest, opts ...grpc.CallOption) (*Academy, error) {
	out := new(Academy)
	err := c.cc.Invoke(ctx, "/grabber.AcademyService/GetAcademy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *academyServiceClient) ListAcademies(ctx context.Context, in *ListAcademiesRequest, opts ...grpc.CallOption) (*ListAcademiesResponse, error) {
	out := new(ListAcademiesResponse)
	err := c.cc.Invoke(ctx, "/grabber.AcademyService/ListAcademies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcademyServiceServer is the server API for AcademyService service.
type AcademyServiceServer interface {
	GetAcademy(context.Context, *GetAcademyRequest) (*Academy, error)
	ListAcademies(context.Context, *ListAcademiesRequest) (*ListAcademiesResponse, error)
}

// UnimplementedAcademyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAcademyServiceServer struct {
}

func (*UnimplementedAcademyServiceServer) GetAcademy(context.Context, *GetAcademyRequest) (*Academy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAcademy not implemented")
}
func (*UnimplementedAcademyServiceServer) ListAcademies(context.Context, *ListAcademiesRequest) (*ListAcademiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAcademies not implemented")
}

func RegisterAcademyServiceServer(s *grpc.Server, srv AcademyServiceServer) {
	s.RegisterService(&_AcademyService_serviceDesc, srv)
}

func _AcademyService_GetAcademy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAcademyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademyServiceServer).GetAcademy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grabber.AcademyService/GetAcademy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademyServiceServer).GetAcademy(ctx, req.(*GetAcademyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AcademyService_ListAcademies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAcademiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcademyServiceServer).ListAcademies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grabber.AcademyService/ListAcademies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcademyServiceServer).ListAcademies(ctx, req.(*ListAcademiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AcademyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grabber.AcademyService",
	HandlerType: (*AcademyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAcademy",
			Handler:    _AcademyService_GetAcademy_Handler,
		},
		{
			MethodName: "ListAcademies",
			Handler:    _AcademyService_ListAcademies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/academy.proto",
}
