// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: pb/workload.proto

package grabber

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Workload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject      string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Session      string `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Hours        int32  `protobuf:"varint,3,opt,name=hours,proto3" json:"hours,omitempty"`
	Teacher      string `protobuf:"bytes,4,opt,name=teacher,proto3" json:"teacher,omitempty"`
	LesionsType  string `protobuf:"bytes,5,opt,name=lesionsType,proto3" json:"lesionsType,omitempty"`
	ControlsType string `protobuf:"bytes,6,opt,name=controlsType,proto3" json:"controlsType,omitempty"`
}

func (x *Workload) Reset() {
	*x = Workload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Workload) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Workload) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

func (x *Workload) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *Workload) GetLesionsType() string {
	if x != nil {
		return x.LesionsType
	}
	return ""
}

func (x *Workload) GetControlsType() string {
	if x != nil {
		return x.ControlsType
	}
	return ""
}

type GetGroupWorkloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId     int32  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ControlType string `protobuf:"bytes,2,opt,name=control_type,json=controlType,proto3" json:"control_type,omitempty"`
	Session     string `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Page        int32  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetGroupWorkloadRequest) Reset() {
	*x = GetGroupWorkloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupWorkloadRequest) ProtoMessage() {}

func (x *GetGroupWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetGroupWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{1}
}

func (x *GetGroupWorkloadRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupWorkloadRequest) GetControlType() string {
	if x != nil {
		return x.ControlType
	}
	return ""
}

func (x *GetGroupWorkloadRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *GetGroupWorkloadRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetGroupWorkloadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Workload `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetGroupWorkloadResponse) Reset() {
	*x = GetGroupWorkloadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGroupWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupWorkloadResponse) ProtoMessage() {}

func (x *GetGroupWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupWorkloadResponse.ProtoReflect.Descriptor instead.
func (*GetGroupWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{2}
}

func (x *GetGroupWorkloadResponse) GetData() []*Workload {
	if x != nil {
		return x.Data
	}
	return nil
}

type GroupWorkloadItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year       int32  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Group      string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	GroupId    int32  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Speciality string `protobuf:"bytes,4,opt,name=speciality,proto3" json:"speciality,omitempty"`
	CountAll   int32  `protobuf:"varint,5,opt,name=count_all,json=countAll,proto3" json:"count_all,omitempty"`
	Curriculum string `protobuf:"bytes,6,opt,name=curriculum,proto3" json:"curriculum,omitempty"`
}

func (x *GroupWorkloadItem) Reset() {
	*x = GroupWorkloadItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupWorkloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupWorkloadItem) ProtoMessage() {}

func (x *GroupWorkloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupWorkloadItem.ProtoReflect.Descriptor instead.
func (*GroupWorkloadItem) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{3}
}

func (x *GroupWorkloadItem) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *GroupWorkloadItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupWorkloadItem) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupWorkloadItem) GetSpeciality() string {
	if x != nil {
		return x.Speciality
	}
	return ""
}

func (x *GroupWorkloadItem) GetCountAll() int32 {
	if x != nil {
		return x.CountAll
	}
	return 0
}

func (x *GroupWorkloadItem) GetCurriculum() string {
	if x != nil {
		return x.Curriculum
	}
	return ""
}

type ListGroupsWorkloadsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FacultyId int32  `protobuf:"varint,1,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	Years     string `protobuf:"bytes,2,opt,name=years,proto3" json:"years,omitempty"`
	Page      int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListGroupsWorkloadsRequest) Reset() {
	*x = ListGroupsWorkloadsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupsWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsWorkloadsRequest) ProtoMessage() {}

func (x *ListGroupsWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupsWorkloadsRequest) GetFacultyId() int32 {
	if x != nil {
		return x.FacultyId
	}
	return 0
}

func (x *ListGroupsWorkloadsRequest) GetYears() string {
	if x != nil {
		return x.Years
	}
	return ""
}

func (x *ListGroupsWorkloadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListGroupsWorkloadsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GroupWorkloadItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListGroupsWorkloadsResponse) Reset() {
	*x = ListGroupsWorkloadsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListGroupsWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsWorkloadsResponse) ProtoMessage() {}

func (x *ListGroupsWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{5}
}

func (x *ListGroupsWorkloadsResponse) GetData() []*GroupWorkloadItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type TeacherWorkloadItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teacher      string `protobuf:"bytes,1,opt,name=teacher,proto3" json:"teacher,omitempty"`
	TeacherQuery string `protobuf:"bytes,2,opt,name=teacherQuery,proto3" json:"teacherQuery,omitempty"`
}

func (x *TeacherWorkloadItem) Reset() {
	*x = TeacherWorkloadItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeacherWorkloadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherWorkloadItem) ProtoMessage() {}

func (x *TeacherWorkloadItem) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherWorkloadItem.ProtoReflect.Descriptor instead.
func (*TeacherWorkloadItem) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{6}
}

func (x *TeacherWorkloadItem) GetTeacher() string {
	if x != nil {
		return x.Teacher
	}
	return ""
}

func (x *TeacherWorkloadItem) GetTeacherQuery() string {
	if x != nil {
		return x.TeacherQuery
	}
	return ""
}

type ListTeachersWorkloadsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DivisionId int32  `protobuf:"varint,1,opt,name=division_id,json=divisionId,proto3" json:"division_id,omitempty"`
	Years      string `protobuf:"bytes,2,opt,name=years,proto3" json:"years,omitempty"`
	Page       int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListTeachersWorkloadsRequest) Reset() {
	*x = ListTeachersWorkloadsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeachersWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersWorkloadsRequest) ProtoMessage() {}

func (x *ListTeachersWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{7}
}

func (x *ListTeachersWorkloadsRequest) GetDivisionId() int32 {
	if x != nil {
		return x.DivisionId
	}
	return 0
}

func (x *ListTeachersWorkloadsRequest) GetYears() string {
	if x != nil {
		return x.Years
	}
	return ""
}

func (x *ListTeachersWorkloadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListTeachersWorkloadsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*TeacherWorkloadItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListTeachersWorkloadsResponse) Reset() {
	*x = ListTeachersWorkloadsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_workload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTeachersWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersWorkloadsResponse) ProtoMessage() {}

func (x *ListTeachersWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_workload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListTeachersWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_pb_workload_proto_rawDescGZIP(), []int{8}
}

func (x *ListTeachersWorkloadsResponse) GetData() []*TeacherWorkloadItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pb_workload_proto protoreflect.FileDescriptor

var file_pb_workload_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x22, 0xb4, 0x01, 0x0a,
	0x08, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x6f,
	0x75, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x6c, 0x65, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x6c, 0x65, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb4,
	0x01, 0x0a, 0x11, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x69, 0x63, 0x75,
	0x6c, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x69,
	0x63, 0x75, 0x6c, 0x75, 0x6d, 0x22, 0x65, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x63, 0x75, 0x6c, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x1b,
	0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f,
	0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x62,
	0x62, 0x65, 0x72, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x53, 0x0a, 0x13, 0x54,
	0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c,
	0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x22, 0x69, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73,
	0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x79, 0x65, 0x61, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x51, 0x0a, 0x1d, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x72, 0x61,
	0x62, 0x62, 0x65, 0x72, 0x2e, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6b,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xba,
	0x02, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a,
	0x13, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c,
	0x6f, 0x61, 0x64, 0x73, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x67, 0x72, 0x61, 0x62,
	0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x57, 0x6f,
	0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x68, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x61,
	0x62, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72,
	0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x26, 0x2e, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x73, 0x57, 0x6f, 0x72, 0x6b, 0x6c, 0x6f, 0x61, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_workload_proto_rawDescOnce sync.Once
	file_pb_workload_proto_rawDescData = file_pb_workload_proto_rawDesc
)

func file_pb_workload_proto_rawDescGZIP() []byte {
	file_pb_workload_proto_rawDescOnce.Do(func() {
		file_pb_workload_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_workload_proto_rawDescData)
	})
	return file_pb_workload_proto_rawDescData
}

var file_pb_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_workload_proto_goTypes = []interface{}{
	(*Workload)(nil),                      // 0: grabber.Workload
	(*GetGroupWorkloadRequest)(nil),       // 1: grabber.GetGroupWorkloadRequest
	(*GetGroupWorkloadResponse)(nil),      // 2: grabber.GetGroupWorkloadResponse
	(*GroupWorkloadItem)(nil),             // 3: grabber.GroupWorkloadItem
	(*ListGroupsWorkloadsRequest)(nil),    // 4: grabber.ListGroupsWorkloadsRequest
	(*ListGroupsWorkloadsResponse)(nil),   // 5: grabber.ListGroupsWorkloadsResponse
	(*TeacherWorkloadItem)(nil),           // 6: grabber.TeacherWorkloadItem
	(*ListTeachersWorkloadsRequest)(nil),  // 7: grabber.ListTeachersWorkloadsRequest
	(*ListTeachersWorkloadsResponse)(nil), // 8: grabber.ListTeachersWorkloadsResponse
}
var file_pb_workload_proto_depIdxs = []int32{
	0, // 0: grabber.GetGroupWorkloadResponse.data:type_name -> grabber.Workload
	3, // 1: grabber.ListGroupsWorkloadsResponse.data:type_name -> grabber.GroupWorkloadItem
	6, // 2: grabber.ListTeachersWorkloadsResponse.data:type_name -> grabber.TeacherWorkloadItem
	1, // 3: grabber.WorkloadService.GetGroupWorkload:input_type -> grabber.GetGroupWorkloadRequest
	4, // 4: grabber.WorkloadService.ListGroupsWorkloads:input_type -> grabber.ListGroupsWorkloadsRequest
	7, // 5: grabber.WorkloadService.ListTeachersWorkloads:input_type -> grabber.ListTeachersWorkloadsRequest
	2, // 6: grabber.WorkloadService.GetGroupWorkload:output_type -> grabber.GetGroupWorkloadResponse
	5, // 7: grabber.WorkloadService.ListGroupsWorkloads:output_type -> grabber.ListGroupsWorkloadsResponse
	8, // 8: grabber.WorkloadService.ListTeachersWorkloads:output_type -> grabber.ListTeachersWorkloadsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_workload_proto_init() }
func file_pb_workload_proto_init() {
	if File_pb_workload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_workload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupWorkloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGroupWorkloadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupWorkloadItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupsWorkloadsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListGroupsWorkloadsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeacherWorkloadItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeachersWorkloadsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_workload_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTeachersWorkloadsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_workload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_workload_proto_goTypes,
		DependencyIndexes: file_pb_workload_proto_depIdxs,
		MessageInfos:      file_pb_workload_proto_msgTypes,
	}.Build()
	File_pb_workload_proto = out.File
	file_pb_workload_proto_rawDesc = nil
	file_pb_workload_proto_goTypes = nil
	file_pb_workload_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WorkloadServiceClient is the client API for WorkloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkloadServiceClient interface {
	GetGroupWorkload(ctx context.Context, in *GetGroupWorkloadRequest, opts ...grpc.CallOption) (*GetGroupWorkloadResponse, error)
	ListGroupsWorkloads(ctx context.Context, in *ListGroupsWorkloadsRequest, opts ...grpc.CallOption) (*ListGroupsWorkloadsResponse, error)
	ListTeachersWorkloads(ctx context.Context, in *ListTeachersWorkloadsRequest, opts ...grpc.CallOption) (*ListTeachersWorkloadsResponse, error)
}

type workloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadServiceClient(cc grpc.ClientConnInterface) WorkloadServiceClient {
	return &workloadServiceClient{cc}
}

func (c *workloadServiceClient) GetGroupWorkload(ctx context.Context, in *GetGroupWorkloadRequest, opts ...grpc.CallOption) (*GetGroupWorkloadResponse, error) {
	out := new(GetGroupWorkloadResponse)
	err := c.cc.Invoke(ctx, "/grabber.WorkloadService/GetGroupWorkload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) ListGroupsWorkloads(ctx context.Context, in *ListGroupsWorkloadsRequest, opts ...grpc.CallOption) (*ListGroupsWorkloadsResponse, error) {
	out := new(ListGroupsWorkloadsResponse)
	err := c.cc.Invoke(ctx, "/grabber.WorkloadService/ListGroupsWorkloads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) ListTeachersWorkloads(ctx context.Context, in *ListTeachersWorkloadsRequest, opts ...grpc.CallOption) (*ListTeachersWorkloadsResponse, error) {
	out := new(ListTeachersWorkloadsResponse)
	err := c.cc.Invoke(ctx, "/grabber.WorkloadService/ListTeachersWorkloads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkloadServiceServer is the server API for WorkloadService service.
type WorkloadServiceServer interface {
	GetGroupWorkload(context.Context, *GetGroupWorkloadRequest) (*GetGroupWorkloadResponse, error)
	ListGroupsWorkloads(context.Context, *ListGroupsWorkloadsRequest) (*ListGroupsWorkloadsResponse, error)
	ListTeachersWorkloads(context.Context, *ListTeachersWorkloadsRequest) (*ListTeachersWorkloadsResponse, error)
}

// UnimplementedWorkloadServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWorkloadServiceServer struct {
}

func (*UnimplementedWorkloadServiceServer) GetGroupWorkload(context.Context, *GetGroupWorkloadRequest) (*GetGroupWorkloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupWorkload not implemented")
}
func (*UnimplementedWorkloadServiceServer) ListGroupsWorkloads(context.Context, *ListGroupsWorkloadsRequest) (*ListGroupsWorkloadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroupsWorkloads not implemented")
}
func (*UnimplementedWorkloadServiceServer) ListTeachersWorkloads(context.Context, *ListTeachersWorkloadsRequest) (*ListTeachersWorkloadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTeachersWorkloads not implemented")
}

func RegisterWorkloadServiceServer(s *grpc.Server, srv WorkloadServiceServer) {
	s.RegisterService(&_WorkloadService_serviceDesc, srv)
}

func _WorkloadService_GetGroupWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).GetGroupWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grabber.WorkloadService/GetGroupWorkload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).GetGroupWorkload(ctx, req.(*GetGroupWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_ListGroupsWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).ListGroupsWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grabber.WorkloadService/ListGroupsWorkloads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).ListGroupsWorkloads(ctx, req.(*ListGroupsWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_ListTeachersWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTeachersWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).ListTeachersWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grabber.WorkloadService/ListTeachersWorkloads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).ListTeachersWorkloads(ctx, req.(*ListTeachersWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkloadService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grabber.WorkloadService",
	HandlerType: (*WorkloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGroupWorkload",
			Handler:    _WorkloadService_GetGroupWorkload_Handler,
		},
		{
			MethodName: "ListGroupsWorkloads",
			Handler:    _WorkloadService_ListGroupsWorkloads_Handler,
		},
		{
			MethodName: "ListTeachersWorkloads",
			Handler:    _WorkloadService_ListTeachersWorkloads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/workload.proto",
}
